baseURL = "https://gitsunmin.github.io/"
languageCode = "ko-kr"
title = "Gitsunmin Blog"
theme = "hugo-profile"
Paginate = 9
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

# [[Menus.main]]
# identifier = "gallery"
# name = "Gallery"
# title = "Blog posts"
# url = "/gallery"
# weight = 2

[params]
title = "Gitsunmin Blog"
description = "Gitsunmin Blog"
favicon = "/images/favicon.png"
useBootstrapCDN = false
mathjax = false
animate = true

[params.font]
fontSize = "1rem"
fontWeight = 400
lineHeight = 1.5
textAlign = "left"

[params.navbar]
align = "ms-auto"
brandName = "Gitsunmin Blog"
disableSearch = false
searchPlaceholder = "제목으로 검색"

[params.navbar.stickyNavBar]
enable = true
showOnScrollUp = true

[params.navbar.menus]
disableAbout = false
disableExperience = false
disableEducation = false
disableProjects = false
disableAchievements = false
disableContact = false

[params.hero]
enable = true
# intro = "👋 👋 👋 👋"
title = "Gitsunmin Blog 👋"
# subtitle = "Welcome to my blog."
# content = """
# 안녕하세요.   
# 평범한 프론트엔드 개발자의 블로그입니다.
# """
image = "/images/home_main.jpeg"

[params.hero.bottomImage]
enable = true

[params.hero.button]
enable = false
name = "Resume"
url = "#"
download = true
newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/gitsunmin"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/gitsunmin"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fas fa-envelope"
url = "mailto:tjsals116@gmail.com"

# [[params.hero.socialLinks.customIcons]]
# icon = "/fav.png"
# url = "https://example.com"

[params.about]
enable = true
title = "About Me"
image = "/images/about_me.png"
content = """
2019년에 Vue로 프론트엔드 개발을 시작하여,   
Electron, React, Flutter 등을 사용하여 다양한 플랫폼에서 개발을 하고있습니다.   
<br />
"""

[params.about.skills]
enable = true
title = "최근 사용중인 기술의 목록입니다."
items = ["React(Next.js)", "React Relay", "TypeScript", "Flutter"]

[params.experience]
enable = false

[params.education]
enable = false
index = false

[params.achievements]
enable = false

[[params.achievements.items]]
title = "Google kickstart runner"
content = "I solved all problems with optimal solution."
url = "https://example.com"
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Facebook Hackathon Winner"
content = "Developed a product using Artificial Intelligence."
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Gitsunmin Blog"
content = "Developed a theme and getting 1K+ downloads per month."
url = "https://github.com/gurusabarish/hugo-profile"
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Microsoft Imagine Runner"
content = "We are developed a product which can help others."

[[params.achievements.items]]
title = "Google Summer of Code"
content = "Contributed to a open source project."
url = "https://example.com"

[params.projects]
enable = false

[[params.projects.items]]
title = "Hugo Profile"
content = "A highly customizable and mobile first Hugo template for personal portfolio and blog."
image = "/images/projects/profile.png"
badges = ["Hugo", "Bootstrap", "Javascript"]

[params.projects.items.featured]
name = "Demo"
link = "https://hugo-profile.netlify.app"

[[params.projects.items.links]]
icon = "fa fa-envelope"
url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/gurusabarish/hugo-profile"

[[params.projects.items.links]]
icon = "fab fa-twitter"
url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

[[params.projects.items]]
title = "Image Converter"
content = "A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django."
image = "/images/projects/converter.jpg"
badges = ["Django", "Bootstrap"]

[params.projects.items.featured]
name = "Demo"
link = "https://django-converter.herokuapp.com"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/gurusabarish/converter"

[[params.projects.items]]
title = "Hugo Profile V2"
content = "A clean and simple Hugo template for personal portfolio and blog."
image = "/images/projects/profile2.jpg"
badges = ["Hugo", "Bootstrap", "Javascript"]

[params.projects.items.featured]
name = "Demo V2"
link = "https://hugo-profile-2.netlify.app"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/gurusabarish/HugoProfileV2"

[params.contact]
enable = false
title = "Contact Me"
# content = ""
email = "tjsals116@gmail.com"
btnName = "Mail me"


[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/gitsunmin"
linkedin = "https://www.linkedin.com/in/gitsunmin"

[params.listPages]
disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.terms]
read = "Read"
toc = "목차"
copyright = "All rights reserved"
pageNotFound = "Page not found"
emailText = "Check out this site"

[socialshare]
enable = false


[params.datesFormat]
article = "2006.01.02"
articleList = "2006.01.02"
articleRecent = "2006.01.02"
