baseURL = "https://gitsunmin.github.io/"
languageCode = "ko-kr"
title = "Gitsunmin Blog"
theme = "hugo-profile"
Paginate = 9
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

# [[Menus.main]]
# identifier = "portfolio"
# name = "Portfolio"
# title = "Portfolio"
# url = "/portfolio"
# weight = 2

[params]
title = "Gitsunmin Blog"
description = "Gitsunmin Blog"
favicon = "/images/favicon.png"
useBootstrapCDN = false
mathjax = false
animate = true
googleSiteVerification = "kETm7W8i9VkwpCzCx8-LKkKiZKp5TINcqV-6VQG7ynM"
gtmId = "GTM-MG4SR53N"

[params.font]
fontSize = "1rem"
fontWeight = 400
lineHeight = 1.5
textAlign = "left"

[params.navbar]
align = "ms-auto"
brandName = "Gitsunmin Blog"
disableSearch = false
searchPlaceholder = "제목으로 검색"

[params.navbar.stickyNavBar]
enable = true
showOnScrollUp = true

[params.navbar.menus]
disableAbout = false
disableExperience = false
disableEducation = false
disableProjects = false
disableAchievements = false
disableContact = false

[params.hero]
enable = true
# intro = "👋 👋 👋 👋"
title = "Gitsunmin Blog"
# subtitle = "Welcome to my blog."
# content = """
# 안녕하세요.   
# 평범한 프론트엔드 개발자의 블로그입니다.
# """
image = "/images/home_main.jpeg"

[params.hero.bottomImage]
enable = true

[params.hero.button]
enable = false
name = "Resume"
url = "#"
download = true
newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/gitsunmin"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/gitsunmin"

[params.about]
enable = false
title = "About Me"
image = "/images/me/profile.gif"
content = """
<br/>
<br/>
<br/>
안녕하세요. 👋 <br/> 프론트엔드 개발자 김선민입니다.
<br />
"""

[params.about.skills]
enable = false
title = "최근 사용중인 기술의 목록입니다."
items = ["React(Next.js)", "React Relay", "TypeScript", "Flutter"]

[params.experience]
enable = false

[params.education]
enable = false
index = false

[params.achievements]
enable = false

[params.projects]
enable = false

[params.contact]
enable = false
title = "Contact Me"
# content = ""
email = "tjsals116@gmail.com"
btnName = "Mail me"


[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/gitsunmin"
linkedin = "https://www.linkedin.com/in/gitsunmin"

[params.listPages]
disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.terms]
read = "Read"
toc = "목차"
copyright = "All rights reserved"
pageNotFound = "Page not found"
emailText = "Check out this site"

[socialshare]
enable = false


[params.datesFormat]
article = "2006.01.02"
articleList = "2006.01.02"
articleRecent = "2006.01.02"
