/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as LayoutImport } from './routes/_layout'
import { Route as BooksImport } from './routes/_books'
import { Route as LayoutProjectsImport } from './routes/_layout.projects'
import { Route as LayoutInterviewImport } from './routes/_layout/interview'
import { Route as LayoutCareersImport } from './routes/_layout/careers'
import { Route as BooksProjectsFoodspringImport } from './routes/_books/projects/foodspring'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const BooksRoute = BooksImport.update({
  id: '/_books',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutProjectsRoute = LayoutProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInterviewRoute = LayoutInterviewImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCareersRoute = LayoutCareersImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => LayoutRoute,
} as any)

const BooksProjectsFoodspringRoute = BooksProjectsFoodspringImport.update({
  id: '/projects/foodspring',
  path: '/projects/foodspring',
  getParentRoute: () => BooksRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_books': {
      id: '/_books'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BooksImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/_layout/careers': {
      id: '/_layout/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof LayoutCareersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/interview': {
      id: '/_layout/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof LayoutInterviewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsImport
      parentRoute: typeof LayoutImport
    }
    '/_books/projects/foodspring': {
      id: '/_books/projects/foodspring'
      path: '/projects/foodspring'
      fullPath: '/projects/foodspring'
      preLoaderRoute: typeof BooksProjectsFoodspringImport
      parentRoute: typeof BooksImport
    }
  }
}

// Create and export the route tree

interface BooksRouteChildren {
  BooksProjectsFoodspringRoute: typeof BooksProjectsFoodspringRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksProjectsFoodspringRoute: BooksProjectsFoodspringRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

interface LayoutRouteChildren {
  LayoutCareersRoute: typeof LayoutCareersRoute
  LayoutInterviewRoute: typeof LayoutInterviewRoute
  LayoutProjectsRoute: typeof LayoutProjectsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCareersRoute: LayoutCareersRoute,
  LayoutInterviewRoute: LayoutInterviewRoute,
  LayoutProjectsRoute: LayoutProjectsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRouteWithChildren
  '/settings': typeof SettingsRoute
  '/careers': typeof LayoutCareersRoute
  '/interview': typeof LayoutInterviewRoute
  '/projects': typeof LayoutProjectsRoute
  '/projects/foodspring': typeof BooksProjectsFoodspringRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRouteWithChildren
  '/settings': typeof SettingsRoute
  '/careers': typeof LayoutCareersRoute
  '/interview': typeof LayoutInterviewRoute
  '/projects': typeof LayoutProjectsRoute
  '/projects/foodspring': typeof BooksProjectsFoodspringRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_books': typeof BooksRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_layout/careers': typeof LayoutCareersRoute
  '/_layout/interview': typeof LayoutInterviewRoute
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_books/projects/foodspring': typeof BooksProjectsFoodspringRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/settings'
    | '/careers'
    | '/interview'
    | '/projects'
    | '/projects/foodspring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/settings'
    | '/careers'
    | '/interview'
    | '/projects'
    | '/projects/foodspring'
  id:
    | '__root__'
    | '/'
    | '/_books'
    | '/_layout'
    | '/settings'
    | '/_layout/careers'
    | '/_layout/interview'
    | '/_layout/projects'
    | '/_books/projects/foodspring'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BooksRoute: typeof BooksRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BooksRoute: BooksRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  SettingsRoute: SettingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_books",
        "/_layout",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_books": {
      "filePath": "_books.tsx",
      "children": [
        "/_books/projects/foodspring"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/careers",
        "/_layout/interview",
        "/_layout/projects"
      ]
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/_layout/careers": {
      "filePath": "_layout/careers.tsx",
      "parent": "/_layout"
    },
    "/_layout/interview": {
      "filePath": "_layout/interview.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects": {
      "filePath": "_layout.projects.tsx",
      "parent": "/_layout"
    },
    "/_books/projects/foodspring": {
      "filePath": "_books/projects/foodspring.tsx",
      "parent": "/_books"
    }
  }
}
ROUTE_MANIFEST_END */
