/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InterviewImport } from './routes/interview'
import { Route as CareersImport } from './routes/careers'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutTilIndexImport } from './routes/_layout/til/index'
import { Route as LayoutTilCategorySlugImport } from './routes/_layout/til/$category.$slug'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const InterviewRoute = InterviewImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRoute,
} as any)

const CareersRoute = CareersImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutTilIndexRoute = LayoutTilIndexImport.update({
  id: '/til/',
  path: '/til/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTilCategorySlugRoute = LayoutTilCategorySlugImport.update({
  id: '/til/$category/$slug',
  path: '/til/$category/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersImport
      parentRoute: typeof rootRoute
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewImport
      parentRoute: typeof rootRoute
    }
    '/_layout/til/': {
      id: '/_layout/til/'
      path: '/til'
      fullPath: '/til'
      preLoaderRoute: typeof LayoutTilIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/til/$category/$slug': {
      id: '/_layout/til/$category/$slug'
      path: '/til/$category/$slug'
      fullPath: '/til/$category/$slug'
      preLoaderRoute: typeof LayoutTilCategorySlugImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutTilIndexRoute: typeof LayoutTilIndexRoute
  LayoutTilCategorySlugRoute: typeof LayoutTilCategorySlugRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutTilIndexRoute: LayoutTilIndexRoute,
  LayoutTilCategorySlugRoute: LayoutTilCategorySlugRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRouteWithChildren
  '/careers': typeof CareersRoute
  '/interview': typeof InterviewRoute
  '/til': typeof LayoutTilIndexRoute
  '/til/$category/$slug': typeof LayoutTilCategorySlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRouteWithChildren
  '/careers': typeof CareersRoute
  '/interview': typeof InterviewRoute
  '/til': typeof LayoutTilIndexRoute
  '/til/$category/$slug': typeof LayoutTilCategorySlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/careers': typeof CareersRoute
  '/interview': typeof InterviewRoute
  '/_layout/til/': typeof LayoutTilIndexRoute
  '/_layout/til/$category/$slug': typeof LayoutTilCategorySlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/careers'
    | '/interview'
    | '/til'
    | '/til/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/careers' | '/interview' | '/til' | '/til/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/careers'
    | '/interview'
    | '/_layout/til/'
    | '/_layout/til/$category/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  CareersRoute: typeof CareersRoute
  InterviewRoute: typeof InterviewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LayoutRoute: LayoutRouteWithChildren,
  CareersRoute: CareersRoute,
  InterviewRoute: InterviewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/careers",
        "/interview"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/til/",
        "/_layout/til/$category/$slug"
      ]
    },
    "/careers": {
      "filePath": "careers.tsx"
    },
    "/interview": {
      "filePath": "interview.tsx"
    },
    "/_layout/til/": {
      "filePath": "_layout/til/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/til/$category/$slug": {
      "filePath": "_layout/til/$category.$slug.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
